version: "3"

services:
  golang:
    build:
      context: .
    container_name: ${PROJECT_NAME}
    ports:
      - 8888:8888
    restart: always
    environment:
      - ENV=${ENV}
      - PROJECT_NAME=${PROJECT_NAME}
      - CHANNEL_SECRET=${CHANNEL_SECRET}
      - CHANNEL_TOKEN=${CHANNEL_TOKEN}
    depends_on:
      - mysql
    working_dir: /go/src/${PROJECT_NAME}
    volumes:
      - .:/go/src/${PROJECT_NAME}
    networks:
      - ever-book-service
    command: "fresh runner.conf"
  mysql:
    image: mysql:5.7
    container_name: ${PROJECT_NAME}-db
    restart: always
    volumes:
      - /home/winston/DB/${PROJECT_NAME}:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: everbook
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
    networks:
      - ever-book-service

networks:
  ever-book-service:
    external: true