
app = "ever-book"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/go"]

[env]
  ENV="prod"
  CHANNEL_SECRET="11ac8e11dbeb96fab7e4d43b50524353"
  CHANNEL_TOKEN="ovBKMNk3RWTNdZfCzcoEaSxCqPKhXrL5uAR8wZDEWbUD62EoSlevmuv0CTTsYrXIFcl+mc90amQWeCPWL6377YrN4JAxf8J4uNdu6IomQ4Rji4tqqN7JZLFtdSjrfeABPlRF5GQnaIKZh/Jhyh/ASgdB04t89/1O/w1cDnyilFU="

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
